apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: nv-embedqa-e5-v5
  namespace: nim-service
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.3.1
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        profiles:
        - all
  storage:
    pvc:
      create: true
      storageClass: efs
      size: "50Gi"
      volumeAccessMode: ReadWriteMany
  resources: {}
  nodeSelector:
    NodeGroupType: gpu-node-pool
    type: karpenter
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: meta-llama-3-2-1b-instruct
  namespace: nim-service
spec:
  source:
    ngc:
      modelPuller: "nvcr.io/nim/meta/llama-3.2-1b-instruct:1.6.0"
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        engine: tensorrt_llm
        profiles:
        - all
  storage:
    pvc:
      create: true
      storageClass: efs
      size: "50Gi"
      volumeAccessMode: ReadWriteMany
  resources: {}
  nodeSelector:
    NodeGroupType: gpu-node-pool
    type: karpenter
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists