apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: meta-llama-3-2-1b-instruct
  namespace: nim-service
spec:
  annotations:
    prometheus.io/scrape: "true"
  image:
    repository: nvcr.io/nim/meta/llama-3.2-1b-instruct
    tag: "1.6.0"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: meta-llama-3-2-1b-instruct
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: ClusterIP
      port: 8000
  scale:
    enabled: true
    hpa:
      maxReplicas: 3
      minReplicas: 1
      metrics:
      - type: Object
        object:
          metric:
            name: request_success_total
          describedObject:
            apiVersion: v1
            kind: Service
            name: meta-llama-3-2-1b-instruct
          target:
            type: Value
            value: 10
  nodeSelector:
    NodeGroupType: gpu-node-pool
    type: karpenter
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nv-embedqa-e5-v5
  namespace: nim-service
spec:
  image:
    repository: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2
    tag: 1.3.1
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nv-embedqa-e5-v5
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: ClusterIP
      port: 8000
  nodeSelector:
    NodeGroupType: gpu-node-pool
    type: karpenter
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
