apiVersion: v1
kind: Namespace
metadata:
  name: nim-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nim-operator
  namespace: nim-operator
spec:
  interval: 30m
  dependsOn:
    - name: node-feature-discovery
      namespace: node-feature-discovery
  chart:
    spec:
      chart: k8s-nim-operator
      version: "v1.0.1"
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: default
      interval: 12h
