apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: default
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia
  namespace: default
spec:
  interval: 24h
  url: https://helm.ngc.nvidia.com/nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: "v0.17.3"
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: default
      interval: 12h
  values:
    driver:
      enabled: "false"
